### ISSUE TITLE
Value errors when checking validity of matrix

### ISSUE THREAD

**Issue by EDWhyte** [baharev/safe-eliminations#2]
The following error is encountered when running 

- rpc_api.fine_dulmage_mendelsohn
- heap_md.hessenberg
- bordered.to_bordered_form

`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

The errors originate from the following lines:
dm_decomp.py line 148
order_util.py line 104 + 105

**Comment by baharev** [comment]
These files do not exist in this project.
